export default {

    //add id to the and replace * with the number of subjects
    // ****** it's important don't igonre it **********
    id: "services-2",

    title: "Bar in out lost",

    content: `
       

	
	<div class="entry-content clear" itemprop="text">

		
		<div class="WordSection1">
<p class="MsoNormal" dir="RTL" style="text-align: center;line-height: normal;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 18.0pt;font-family: 'Times New Roman',serif">Bar in out lost</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">وصف الخدمة:</span></b><b></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">&nbsp;</span></b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">يمكن إيقاف الخط المسبق </span><span lang="AR-SY" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">أ</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">و اللاحق الدفع عن&nbsp;الاتصالات الصادرة و الواردة في حالة الضياع أو السرقة فقط لمدة أقصاها شهر&nbsp;من تاريخ الايقاف.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">يمكن للخط المتوقف الاتصال بالأرقام المجانية و الـ&nbsp; 111</span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاشتراك بالخدمة:</span></b><b></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">التأكد من </span><span lang="AR-SY" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">ا</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">سم المشترك الكامل و الرقم الوطني للهوية الشخصية.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">الحصول على كلمة السر و رقم للمتابعة.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">ايقاف الخط سيتم من 2-6 ساعات.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">مدة الايقاف شهر كحد اقصى و في حال عدم اعادة تفعيل الخط سيخضع لدورة الحياة المعتادة.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">لتغيير الشريحة &nbsp;يجب مراجعة المركز من قبل صاحب الخط مع الهوية الشخصية.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">كلفة استبدال الشريحة.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">الخط المسبق الدفع موجود ضمن فترة الصلاحية 90 يوم من آخر استهلاك من الرصيد تجنبا لخسارة الخط.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">في حال عدم اعادة تفعيل الخط سيخضع الخط لدورة الحياة المعتادة.</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: Wingdings">Ø<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">استمرار احتساب الاشتراكات الشهرية للخدمات و الميزات المفعلة على الخط.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">شروط الأشتراك: </span></b><b></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">حضور صاحب العلاقة مع احد الأوراق الثبوتية التالية (يرجى مراجعة صفحة الأوراق الثبوتية المقبولة يرجى مراجعة صفحة الوكالة العامة و الخاصة)</span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">الخدمات الواجب توافرها</span></b><b><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">:</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">&nbsp;</span></b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">ان يكون الخط المسبق الدفع بفترة الصلاحية أو الاستقبال</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">تفعيل الخدمة</span></b><b><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">:</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">1- من خلال خدمة الزبائن: </span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">التأكد من اسم المشترك الكامل و الرقم الوطني للهوية الشخصية الجديدة&nbsp;</span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">)</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">في حال رقم الهوية المسجل في البرنامج قديم يتم تقديم طلب تعديل لبيانات المشترك في حال وجود الهوية الشخصية الجديدة</span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">.(</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SY" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">وفي حال تواصله مع قسم الاتصالات يتم التأكد من الاسم الكامل والرقم الوطني.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">إدخال الطلب على&nbsp; برنامج </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CRM</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> و سبب الإيقاف.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">إعلام المشترك عن استمرار احتساب الاشتراك الشهري للميزات المأجورة.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">اعلام المشترك ان مدة الايقاف شهر و في حال عدم اعادة تفعيل الخط سيخضع الخط لدورة الحياة المعتادة&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">ايقاف الخط مباشرة على الـ </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CX</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">.&nbsp;</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">7.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">اضافة ملاحظة على الـ </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CX</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> &nbsp;بسبب الإيقاف و كلمة السر ورقم هاتف آخر للمشترك </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">)</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">وذلك للاتصال به في حال العثور على الخط.</span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">(</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl;margin: 0in .5in .0001pt 0in">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">ملاحظة</span></b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">: جميع الملاحظات السابقة تكون </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">Open</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> والموظف الذي يفعّل الخط أو يبدل البطاقة هو المسؤول عن إغلاق الملاحظة.<br>
<!-- [if !supportLineBreakNewLine]--><br>
<!--[endif]--></span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">2- المجيب الآلي الخاص بمركز الاتصالات (111) </span></b></p>
<ol start="1" type="1">
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">الدخول إلى خيار إيقاف الخط بسبب الضياع عبر الضغط على&nbsp; الرقم</span></li>
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">سيتم طلب رقم الخط المراد إيقافه إضافة إلى رقم الهوية الوطني</span></li>
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">في حال كان أحد الرقمين خطأ أو عدم التوافق بين رقم الخط ورقم الهوية سيتم الطلب بإعادة إدخال الرقم الصحيح مرة أخرى. في حال عدم إدخال الأرقام الصحيحة للمرة الثانية سيتم الإعتذار وإنهاء الإتصال.</span></li>
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">في حال كان رقم المتصل مفعل عليه خدمة حجب الرقم لن يتم سماع هذا الخيار عند الإتصال بال 111 .</span></li>
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">لدى إدخال الأرقام بشكل صحيح سيتم إعلام المشترك أنه سيتم إيقاف الخط بأسرع وقت و انه لإعادة تفعيل الخط يجب الاتصال بخدمة الزبائن أو مراجعة أحد مراكز الخدمة</span></li>
</ol>
<p class="MsoListParagraph" dir="RTL" style="margin-right: .5in;margin-bottom: 12.0pt;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">سيتم إيقاف الخط ومن ثم إضافة </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">Tickler</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> تلقائياً&nbsp;تتضمن إيقاف الخط عبر المجيب الألي بسبب ضياع الجهاز و الرقم الذي تم الإتصال منه</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl;margin: 0in .5in .0001pt 0in">
<p class="MsoListParagraph" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">7.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">المدة اللازمة لتفعيل الخدمة من 2-6 ساعات.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">ملاحظة</span></b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> : عند إيقاف الخط عن طريق المجيب الآلي ( 111 )</span> <span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">&nbsp;سيتم إيقاف الخط &nbsp;</span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">Bar in out</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> سواء كان خط عادي أو </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">Speed</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">3- الرمز #159*</span></b><b><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">:</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">1- يتم طلب الرمز <b>#</b>159<b>*</b></span><b> </b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">من رقم </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> &nbsp;باسم للمشترك حيث تظهر القائمة التالية :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl">
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">2- اختيار البند رقم 2) حيث يطلب من المشترك ادخال الرقم المراد ايقافه :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl">
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">3- ثم يطلب من المشترك ادخال الرقم الوطني للهوية :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl">
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">4- ثم سيتم تأكيد الرقم الذي سيتم ايقافه :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"><br>
</span>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">لدى إدخال المعلومات بشكل صحيح سيتم ارسال رسالة للمشترك&nbsp; :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl">
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">سيتم إيقاف الخط عن الاتصالات الصادرة والواردة ومن ثم إضافة </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">Tickler</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> تلقائياً تتضمن إيقاف الخط بسبب ضياع الجهاز وكلمة السر ( نفس الرقم الذي تم ايقافه ) ورقم المتابعة الذي تم ادخاله من قبل المشترك.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl">
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">المدة اللازمة لتفعيل الخدمة من 2-6 ساعات.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">لإعادة تفعيل الخط يجب الاتصال بخدمة الزبائن أو مراجعة أحد مراكز الخدمة .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">الغاء&nbsp; الخدمة</span></b><b><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CSC </span></b><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">&nbsp;&amp; </span></b><b><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">VIP</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SY" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">في حال التواصل مع قسم الاتصالات: </span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">التأكد من رقم الهوية الشخصية ومن كلمة السر معاً ، عدا ذلك يطلب من المشترك الحضور شخصياً إلى المركز مع الهوية.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .25in;text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">في حال مراجعة المركز: ضرورة توفر&nbsp;اسم المشترك الكامل و الهوية الشخصية الجديدة&nbsp; و لايتم طلب كلمة السر</span></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">لا يتم تفعيل الخط&nbsp; في حال عدم توفر الهوية الشخصية إلا بالاعتماد على اسم المشترك الكامل بالإضافة إلى رقم الهوية الجديدة وكلمة السر</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">التأكد من تسديد كافة الفواتير المستحقة ومن عدم وجود أي ملاحظة على الخط تفيد بعدم تفعيل الخط.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">إعادة تفعيل الخط مباشرة.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">إلغاء الملاحظة المدونة على الـ </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CX</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> والتي تفيد بإيقاف الخط.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">إدخال الطلب على&nbsp; برنامج </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CRM</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">7.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">المدة اللازمة لإلغاء الخدمة 12 ساعة</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">8.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">رقم الهوية المسجل في البرنامج </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CX</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> قديم يتم تفعيل الخط اعتمادا على الهوية الشخصية الجديدة حصرا بعد تقديم طلب تجديد البيانات ولا يتم قبول أي بديل عن الهوية الشخصية</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">ملاحظة هامة :&nbsp;&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">_لاعادة تفعيل الخط المتوقف بسبب الضياع عن طريق قائمة *159# من خلال مركز الاتصالات :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">يجب سؤال المشترك عن رقم المتابعة الذي تم ادخاله عند الايقاف بدلاً من كلمة السر كونه يتم بشكل تلقائي اعتبار كلمة السر (الرقم الذي تم ايقافه) بالاضافة لكافة المعلومات المطلوبة في مثل هذه الحالات.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">_ لاعادة تفعيل الخط المتوقف بسبب الضياع عن طريق المجيب الآلي من خلال مركز الاتصالات :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">يجب سؤال المشترك عن الرقم الذي تم الإتصال منه بدلاً عن كلمة السر بالإضافة لكافة البيانات المطلوبة في مثل هذه الحالات</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: normal;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">معلومات اضافية:</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">في حال طلب ايقاف خط مسبق الدفع وهو في مرحلة التجميد يتم توجيه المشترك الى أحد مراكز الخدمة مع الهوية الشخصية الجديدة لإجراء إعادة تفعيل للخط بالإضافة إلى تغيير السيم.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">تذكير المشترك بموعد انتهاء فترة الـ 90 يوم (أو الاستقبال) وإعلام المشترك بأنه سيتم احتساب فترة الـ 90 يوم بشكل طبيعي ولن تتأثر بالايقاف.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">إعلام المشترك عن استمرار احتساب الاشتراك الشهري للميزات المأجورة مثل ( سوبر كليب، الخدمات الاخبارية…).</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">يمكن استقبال الليرات المحولة إلى الخط الذي تم إيقافه.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">يمكن إيقاف الخط عبر المجيب الآلي (111) و لكن لا يمكن إعادة تفعيل الخط إلا عبر موظف خدمة الزبائن (111 أو </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">CSC</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> )</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">لا يمكن ايقاف الخط بطلب من المشترك و ذلك لان الايقاف يكون حصراً بحال ضياع الجهاز او سرقته.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">7.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">تذكير المشترك عند إيقاف الخط بضرورة تسديد الفاتورة بالموعد المحدد حتى لا يترتب غرامة تأخير.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">8.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">إعلام المشترك عن خدمة الايقاف المؤقت في حال أراد إيقاف الخط اللاحق الدفع أكثر من شهر .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">9.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">عند تفعيل الخط اللاحق الدفع &nbsp;يجب إ<b>غلاق الملاحظة</b> و <b>تفعيل الخط &nbsp; </b></span><b><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">De Bar In Out</span></b><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">&nbsp;, مع ضرورة تنبيه المشترك للحد الائتماني لخطه .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">10.<span style="font: 7.0pt 'Times New Roman'">&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">لن يتم تفعيل الخط تلقائياً بعد انتهاء الشهر و إنما ستخضع الخطوط لدورة حياة الخط كالمعتاد للخطوط اللاحقة و المسبقة الدفع&nbsp; و آلية الالغاء</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: normal;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;font-family: 'Times New Roman',serif">11.<span style="font: 7.0pt 'Times New Roman'">&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">عند طلب اعادة تفعيل خط عليه ملاحظات قديمة </span><span dir="LTR" style="font-size: 12.0pt;font-family: 'Times New Roman',serif">Request / Hotline /SIM Lose/ Don’t react</span><span lang="AR-SA" style="font-size: 12.0pt;font-family: 'Times New Roman',serif"> &nbsp; &nbsp;يجب تفعيل الخط وإغلاق هذه الملاحظات.</span></p>
</div>

		
		
			</div><!-- .entry-content .clear -->
</div>
    `,

  

    // color of Prepaid :
    // image: "linear-gradient(135deg, #673AB7, #7E57C2)"
    // image: "linear-gradient(135deg, #ffcc00, #e6b800)"
    // image: "linear-gradient(135deg, #ff9900, #e68a00)"
    // image: "linear-gradient(135deg, #ffcc00, #cc9900)"
    
    // color of postpaid :
    // image: "linear-gradient(135deg, #4527A0, #4527A0)"
    // image: "linear-gradient(135deg, #ff0000, #cc0000)"
    // image: "linear-gradient(135deg, #cc0000, #990000)"
  
    // color of services :
    // image: "linear-gradient(135deg, #C2185B, #E91E63)"
    image: "linear-gradient(135deg, #C562AF, #B33791)"
    // image: "linear-gradient(135deg, #00678f, #004d6f)"
    // image: "linear-gradient(135deg, #0088cc, #006699)"
    // image: "linear-gradient(135deg, #0099cc, #0077aa)"

};