export default {

    //add id to the and replace * with the number of subjects
    // ****** it's important don't igonre it **********
    id: "postpaid-34",

    title: "Delegation",

    content: `	
	
<div class="ast-post-format- single-layout-1">

	
	

	
	<div class="entry-content clear" itemprop="text">

		
		<div class="WordSection1">
<p class="MsoNormal" style="text-align: center;line-height: 115%" align="center"><b><span style="font-size: 20.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">Delegation</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">وصف الخدمة:</span></b><b></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يمكن للمشترك&nbsp; تفويض شخص أو عدة أشخاص للقيام بكافة الإجراءات&nbsp;أو جزء من الإجراءات المتعلقة بخطه، دون حضوره إلى المركز.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p style="direction: rtl"><strong><u>ملاحظة هامة:</u></strong></p>
<p style="direction: rtl"><strong>اعتباراً من تاريخ 27.11.2013 تم إيقاف إمكانية تفويض مشترك آخر بتبديل السيم وتقديم طلب واستلام الفاتورة التفصيلية والتنازل ليكون عن طريق الوكالة القانونية حصراً (بغض النظر عن تاريخ التفويض).</strong></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاشتراك بالخدمة:</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in .0001pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">مراجعة صاحب الخط مع الوثائق الثبوتية المطلوبة والوثائق الثبوتية للمفوض اليه دون حضور المفوض إليه.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in .0001pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">تكلفة التفويض مع قيمة الطوابع.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in .0001pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">اعلام المشترك أن التفويض الحديث لايشمل التنازل وتغيير الشريحة وطلب التفصيلي.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in .0001pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">التوقيع والبصمة على الطلب من قبل المشترك والصاق الطابع المالي لطلب التفويض.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in .0001pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">لا داعي لارفاق صورة عن هوية صاحب الخط لدى مراجعة المفوض مركز الخدمة لتنفيذ أي اجراء على الخط.</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in .0001pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">التأكد من تواريخ حالات التفويض وخاصة حالات التفويض القديمة للتأكد من امكانية تنفيذ الاجراء أو لا.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاستفسار عن الخدمة :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in 8.0pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol;color: white">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">مراجعة المشترك المركز مع الهوية.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in 8.0pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">كلفة التفويض 5800&nbsp; (5000 ليرة طابع على العقد + 800 تضاف على اول فاتورة بعد التفويض)</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">.</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl;margin: 0in .75in 8.0pt 0in"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">إعلام المشترك ان التفويض الحديث لا يشمل التنازل و تغيير الشريحة و طلب التفصيلي</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">شروط الأشتراك:</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">حضور صاحب العلاقة شخصياً مع احد الأوراق الثبوتية التالية:</span></p>
<div align="right">
<table class="MsoNormalTable" dir="rtl" style="width: 789.75pt;border-collapse: collapse" border="0" width="1053" cellspacing="0" cellpadding="0">
<tbody>
<tr style="height: 251.05pt">
<td style="width: 431.5pt;border: solid windowtext 1.0pt;padding: 0in 5.4pt 0in 5.4pt;height: 251.05pt" valign="top" width="575">
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">الاشخاص مكتومي القيد:</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">بالنسبة للأشخاص مكتومي القيد اللذين لا يحملون وثائق ثبوتية فلا يمكن تخصيصهم&nbsp; بخطوط هاتفية خليوية (علماً أن وزارة الداخلية لا تمنح المكتومين الغير مسجلين في السجلات السورية أو سجلات أجانب الحسكة&nbsp; أي وثيقة ) .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">يمكن الاستعاضة عن إجراء تفويض في حال كان المشترك قد أجرى وكالة عامة أو خاصة للمفوض مع العلم أنه يجب ذكر الخدمة المراد التفويض بها بشكل واضح.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">الشركات أو الجهات العامة والحكومية أو السفارات</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يتم قبول تفويض خطي أو كتاب&nbsp; موقع من قبل الشخص المسؤول و مختوم بختم الجهة المفوضة و مذكور فيه اسم الشخص المفوض و مرفقا بصورة هوية المفوض.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">المشتركين فئة </span></b><b><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">VIP</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يتم قبول كتاب خطي موقع من صاحب العلاقة يسمي فيه الشخص المفوض.</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">طابع التفويض:</span></b></p>
<ul type="disc">
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">قيمة الطابع &nbsp;: 5000</span></li>
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">ضريبة ادراة محلية 5% : 300</span></li>
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">ضريبة اعادة اعمار 10% ( مقربة الى اقرب&nbsp;مئة) : 500</span></li>
</ul>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يتم إلصاق الطابع على الطلب، أما الضرائب فيتم احتسابها على الفاتورة القادمة (تتم متابعة تسديد قيمة الضرائب من قبل قسم الـ </span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">B.O</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> ) أي لا يتم تحصيلها من المشترك مباشرة.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">معلومات إضافية:</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">لا يمكن للمفوض إجراء تفويض لشخص آخر على نفس الخط مهما كان نوع التفويض.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">لا يمكن تفويض شخص قاصر بأي خدمة.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;إجراءات التفويض و الوكالة من خارج الجمهورية العربية السورية تحتاج لتصديق من وزارة الخارجية في سوريا إضافة لتصديقها من السفارة السورية في الدولة التي صدر التفويض أو الوكالة منها</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">في حال كان فئة الخط </span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">ML</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> يجب التأكد من المشترك من أن التفويض سيشمل جميع الخطوط.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">عند طلب المشترك إجراء تفويض لعدة أرقام باسمه يتم تقديم طلب تفويض واحد لجميع الأرقام و يتم لصق 500 ل.س طوابع على الطلب&nbsp; و الضريبة&nbsp;تحتسب على الفاتورة القادمة&nbsp; ويتم&nbsp; تطبيق نفس الإجراءات عند طلب شركة إجراء تفويض لعدة خطوط باسمها.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يمكن تفويض شخص أجنبي بإجراءات الخط و الأوراق الثبوتية المطلوبة للمفوض الأجنبي هي:</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'"><br>
<span style="color: white">جواز سفر ساري المفعول.<br>
بطاقة إقامة أصولية.</span></span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">7.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">في حال وجود تفويض على الخط اللاحق الدفع و تم تحويل الخط إلى مسبق الدفع فإن التفويض يصبح لاغياً حيث لإن خدمة التفويض غير متوفرة بالنسبة للخطوط المسبقة الدفع.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">8.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">بحال وجود أكثر من مفوض لنفس المشترك يتم إجراء تفويض واحد مع تحديد أسماء المفوضين و الإجراءات المفوضين عنها و إلصاق طابع تفويض واحد ، علما أن الحد الأعلى لعدد المفوضين هو 3 مفوضين و بحال وجود أكثر من 3 مفوضين يجب إجراء تفويض جديد و إلصاق طابع جديد ، أي طلب التفويض سيكون كحد أقصى لمشترك واحد مهما كان عدد الأرقام مع 3 مفوضين و بطابع واحد.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">9.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">لا داعي لارفاق صورة عن هوية صاحب الخط لدى مراجعة المفوض مركز الخدمة لتنفيذ أي إجراء على الخط</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">10.</span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يمكن للوكيل الغاء التفويض بناء على وكالة عامة.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">11.</span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">لا يمكن للمفوض اجراء تنازل عن الخط لنفسه او لغيره ” باستثناء حالات التفويض القديمة”.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">12.</span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">لا يحق للمفوض طلب طباعة فواتير تفصيلية عن اشهر تسبق تاريخ التفويض&nbsp;” باستثناء </span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: blue"></span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">“.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl">
</p><p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">تفعيل الخدمة:</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">حضور المشترك صاحب العلاقة إلى مركز الخدمة مصطحباً الأوراق الثبوتية العائدة له و للمفوض.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">مركز خدمة المشتركين:</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">ادراج حالة على الـ</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">CRM</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> تتضمن : اسم المفوض الثلاثي &nbsp;– رقم هوية المفوض</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"><br>
<!--[endif]--></span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">طباعة الطلب الورقي تلقائيا من الـ</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">CRM</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">توقيع المشترك على طلب التفويض مرفقا بصورة ثبوتية لكل من المشترك صاحب العلاقة و المفوض، مع وجود بصمة الإبهام الأيسر على الطلب</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يتم إلصاق الطابع المالي لطلب التفويض.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">توقيع الموظف و مسؤول المركز على الطلب الورقي</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: 1.0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">ارسال الطلب الورقي الى الـ</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">Back Office</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">قسم الـ </span></b><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">Back office</span></b><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> &nbsp;:</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">استلام الطلب الورقي و التأكد من المرفقات.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">إضافة ملاحظة على الـ</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">BSCS&nbsp; CX</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> &nbsp;&nbsp;تتضمن : اسم المفوض – رقم ثبوتيته – صلاحيات المفوض.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">ارسال الطلب الورقي الى قسم الارشيف .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">احتساب رسم التفويض .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">ملاحظات مهمة:</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 10.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">لا يعتبر التفويض سارياً مالم يتم استلام الطلب الورقي&nbsp;وإدراج الملاحظة على الـ</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">CX</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><b><span style="font-size: 10.0pt;line-height: 115%;font-family: Symbol;color: white">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">يتم بشكل يومي التأكد من استلام الطلبات المنفذة في المراكز و تتم المتابعة من قبل مشرف قسم الـ</span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">BO</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> و مشرفي المراكز في حال عدم استلام الطلب<b></b></span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">إلغاء الخدمة:</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">تعبئة طلب إلغاء تفويض في المركز دون إلصاق طوابع.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">إغلاق الملاحظة على برنامج الـ </span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">BSCS CX</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">إدخال الطلب على&nbsp;برنامج </span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">CRM</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">.</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: right;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic'">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SY" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">إرسال</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> الطلب إلى قسم الـ </span><span dir="LTR" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white">Filing</span><span lang="AR-SA" style="font-size: 12.0pt;line-height: 115%;font-family: 'MTN Brighter Sans Arabic';color: white"> ليحفظ في ملف المشترك.</span></p>
<p class="MsoNormal" style="line-height: 115%"><span style="font-family: 'MTN Brighter Sans Arabic'">&nbsp;</span></p>
<p class="MsoNormal" style="line-height: 115%">
</p></div>

		
		
			</div><!-- .entry-content .clear -->
</div>

	
</article><!-- #post-## -->

			
		
	</div><!-- #primary -->


	</div>
    `,


    // color of Prepaid :
    // image: "linear-gradient(135deg, #673AB7, #7E57C2)"
    // image: "linear-gradient(135deg, #ffcc00, #e6b800)"
    // image: "linear-gradient(135deg, #ff9900, #e68a00)"
    // image: "linear-gradient(135deg, #ffcc00, #cc9900)"
    
    // color of postpaid :
    image: "linear-gradient(135deg, #4527A0, #4527A0)"
    // image: "linear-gradient(135deg, #ff0000, #cc0000)"
    // image: "linear-gradient(135deg, #cc0000, #990000)"
  
    // color of services :
    // image: "linear-gradient(135deg, #C2185B, #E91E63)"
    // image: "linear-gradient(135deg, #00678f, #004d6f)"
    // image: "linear-gradient(135deg, #0088cc, #006699)"
    // image: "linear-gradient(135deg, #0099cc, #0077aa)"

};