export default {

    //add id to the and replace * with the number of subjects
    // ****** it's important don't igonre it **********
    id: "postpaid-3",

    title: "Line Reservation",

    content: `
        <div class="ast-post-format- ast-no-thumb single-layout-1">

	<div class="entry-content clear" itemprop="text">
		
		<div class="WordSection1">
<p class="MsoNormal" dir="RTL" style="text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-size: 14.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">خدمة حجز رقم عن طريق الرسائل – </span></b><b><span dir="LTR" lang="EN-GB" style="font-size: 14.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Line Reservation</span></b><b></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">وصف الخدمة</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">تمكن خدمة حجز رقم عن طريق الرسائل المشتركين من طلب حجز أي رقم مسبق الدفع أو لاحق الدفع من أي ترميز متوفر (094,095,096) عن طريق الرسائل القصيرة ، و استلام الخط من مراكز الخدمة .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاستفسار عن الخدمة أو الاشتراك بها</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1; mso-yfti-lastrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1.<b>لحجز رقم مسبق الدفع :</b> إرسال رسالة من أي رقم </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> مسبق الدفع أو لاحق الدفع إلى الرقم <b>1445</b> متضمنة الرقم الخليوي بالصيغة الكاملة .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2.كلفة الرسالة للرقم <b>1445</b> من الخط المسبق الدفع و اللاحق الدفع .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">3.سعر الخط المسبق الدفع المحجوز .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">4.<b>لحجز رقم لاحق الدفع :</b> إرسال رسالة من أي رقم </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> مسبق الدفع أو لاحق الدفع إلى الرقم <b>1665</b> متضمنة الرقم الخليوي بالصيغة الكاملة .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">5.كلفة الرسالة للرقم <b>1665</b> من الخط المسبق الدفع و اللاحق الدفع .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">6.سعر الخط اللاحق الدفع المحجوز .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">7.مدة متابعة طلب الحجز .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">8.أقصى مدة للحصول على الخط المحجوز</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">9.بحال الاستفسار عن حجز رقم مشابه للخط الثابت يجب مراعاة النقاط التالية : كتابة الرقم بالصيغة الكاملة مع رمز المحافظة ، يجب شراء الخط بنفس اسم مالك الخط الثابت ، يجب إحضار آخر فاتورة للخط الثابت باسمه .</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">طريقة الحجز :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إرسال رسالة من أي رقم </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> مسبق أو لاحق الدفع ، تتضمن :</span></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الرقم الخليوي المطلوب حجزه بالصيغة الكاملة : 0944222111 .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الرقم الثابت المطلوب حجز رقم مشابه له مع رمز نداء المحافظة : 0112233445 .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لحجز <b>رقم مسبق الدفع :</b> من خلال إرسال الرسالة إلى الرقم <b>1445</b> .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لحجز <b>رقم لاحق الدفع :</b> من خلال إرسال الرسالة إلى الرقم <b>1665</b> .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">رسم الاشتراك و التعرفة :</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سعر الخط الجديد :</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 35.82%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="35%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">نوع الخط</span></b></p>
</td>
<td style="width: 19.02%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="19%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">السعر</span></b></p>
</td>
<td style="width: 45.16%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="45%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">التفاصيل</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1;">
<td style="width: 35.82%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="35%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخط <b><u>المسبق الدفع</u></b> المحجوز</span></p>
</td>
<td style="width: 19.02%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="19%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">47,500 ل.س</span></b></p>
</td>
<td style="width: 45.16%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="45%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">45,000 ل.س كلفة الشريحة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">+ 2,500 ل.س كلفة الخدمة</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1;">
<td style="width: 35.82%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="35%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخط <b><u>المسبق الدفع</u></b> المحجوز للمشترك الأجنبي</span></p>
</td>
<td style="width: 19.02%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="19%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">122,500 ل.س</span></b></p>
</td>
<td style="width: 45.16%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="45%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">120,000 ل.س كلفة الشريحة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">+ 2,500 ل.س كلفة الخدمة</span></p>
</td>
</tr>

<tr style="mso-yfti-irow: 2; mso-yfti-lastrow: yes;">
<td style="width: 35.82%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="35%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخط <b><u>اللاحق الدفع</u></b> المحجوز</span></p>
</td>
<td style="width: 19.02%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="19%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">51,050 ل.س</span></b></p>
</td>
<td style="width: 45.16%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="45%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">نفس سعر الخط اللاحق الدفع العادي</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">كلفة الرسالة لطلب حجز الرقم :</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes; height: 20.6pt;">
<td style="width: 16.46%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt; height: 20.6pt;" width="16%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الرقم</span></b></p>
</td>
<td style="width: 83.54%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt; height: 20.6pt;" width="83%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الكلفة للخطوط المسبقة و اللاحقة الدفع</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1; height: 21.05pt;">
<td style="width: 16.46%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt; height: 21.05pt;" width="16%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1445</span></p>
</td>
<td style="width: 83.54%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt; height: 21.05pt;" width="83%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">300 ل.س</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2; mso-yfti-lastrow: yes; height: 20.6pt;">
<td style="width: 16.46%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt; height: 20.6pt;" width="16%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1665</span></p>
</td>
<td style="width: 83.54%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt; height: 20.6pt;" width="83%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">300 ل.س</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">خطوات حجز رقم :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بعد إرسال الرسالة ، يتم إعلام المشترك بأن نتيجة الحجز ستصله برسالة نصية خلال <b><u>72 ساعة عمل</u></b> (سواء بالموافقة أو عدم الموافقة على الحجز) .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن متابعة حالات الحجز و ذلك من خلال الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CRM</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> : </span></p>
<p class="MsoNormal" style="margin-left: .25in;"><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">SMSC Manager – Reserve Number – Search</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .25in; text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">علماً أن البحث متوفر بأربع احتمالات :</span></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><b style="mso-ansi-font-weight: normal;"><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></b><!--[endif]--><b><span dir="LTR" lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-spacerun: yes;">&nbsp;</span></span></b><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Unhandled</span></b><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">:</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> البحث عن الحالات التي لم يتم معالجتها بعد .</span><b></b></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><b style="mso-ansi-font-weight: normal;"><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></b><!--[endif]--><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">GSM</span></b><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> عن طريق إدخال الرقم الذي قام بطلب الحجز سواء برسالة أو عبر البرنامج (</span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Pick Your Number</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">) .</span><b></b></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><b style="mso-ansi-font-weight: normal;"><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></b><!--[endif]--><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Message</span></b><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> حسب نص الرسالة المرسلة .</span><b></b></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l9 level1 lfo1; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><b style="mso-ansi-font-weight: normal;"><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></b><!--[endif]--><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Handled</span></b><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> الحالات التي تمت معالجتها و إبداء الرأي فيها .</span><b></b></p>
</div>
<div></div>
<div class="WordSection1">
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بحال حجز رقم مشابه لرقم الهاتف الأرضي ، ستظهر عبارة على الرقم تؤكد ضرورة توفر فاتورة الهاتف الثابت :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">شروط تسليم الرقم :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند تلقي رسالة الموافقة على الحجز ؛ يجب على المشترك التوجه إلى أي مركز خدمة أو مراكز الوكلاء لاستلام الخط .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يقوم موظف المركز بالتأكد عبر الرابط من الموافقة على الحجز كما هو موضح أعلاه .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بحال طلب شراء الخط <b><u>بنفس</u></b> اسم المشترك الذي قام بعملية الحجز ؛ يجب حضوره شخصياً مع الأوراق الثبوتية المطلوبة .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بحال طلب شراء الخط <b><u>بغير</u></b> اسم المشترك الذي قام بعملية الحجز<span style="mso-spacerun: yes;">&nbsp; </span>؛ يجب وجود المشترك الذي قام بعملية الحجز مع هويته الشخصية و المشترك الذي سيتم تسجيل الخط باسمه مع الأوراق الثبوتية المطلوبة .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">5.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يتم بيع الخط وفق الطرق و الأوراق الثبوتية المطلوبة .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">6.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">قسم المبيعات المباشرة هو المسؤول عن متابعة حالات حجز الرقم الخليوي عبر الرسائل .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">7.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند طلب حجز رقم خليوي مشابه للرقم الثابت يجب شراء الخط بنفس اسم مالك الخط الثابت و بالتالي يجب إحضار آخر فاتورة خط ثابت باسمه إلى المركز، مع مراعاة البندين 3 و 4.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">8.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لا يوجد إمكانية لطلب حجز رقم مشابه للرقم الثابت بصياغة معينة ، حيث يتم إعلام المشترك بالرقم الخليوي المتوفر و الأقرب لرقمه الثابت .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">9.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال تم إرسال رسالة من قبل المشترك متضمنة أكثر من رقم سيتم معالجة أول رقم ضمن الرسالة فقط.</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">10. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بحال وجود حجز باسم مشترك معين كما هو مبين أدناه:</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; text-indent: .5in; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يجب بيع الخط بالاسم الظاهر حصراً و خلال المدة الموضحة بجانب الرقم و بحال الإصرار على شراء الخط بغير اسم أو بعد مرور المدة المحددة يجب أخذ موافقة قسم الـ </span><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; color: #00b050; mso-bidi-language: AR-SY;"></span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عن طريق البريد الالكتروني</span> <span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-spacerun: yes;">&nbsp;</span>.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">طريقة تسليم الرقم :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يتم بيع الرقم عبر برنامج الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CRM</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> عن طريق رابط </span><span lang="EN-GB"></span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> بنفس الطريقة المتبعة مع الأرقام التي تحجز عن طريق قسم المبيعات المباشرة </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Direct Sales</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">و يظهر الإيصال بشكل مشابه لـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Pick Your Pre</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ، كما هو مبين أدناه :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخطوط اللاحقة الدفع :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">رسائل الخدمة :</span></b></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 25.54%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="25%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الحالة</span></b></p>
</td>
<td style="width: 70.08%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="70%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">نص الرسالة</span></b></p>
</td>
<td style="width: 4.38%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="4%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">المرسل</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1;">
<td style="width: 25.54%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="25%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إرسال الرسالة بشكل صحيح سيصل للمشترك مباشرة رسالة الرد</span></p>
</td>
<td style="width: 70.08%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="70%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عزيزي مشترك </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> طلبكم قيد المعالجة سيتم إعلامكم خلال 72 ساعة</span></p>
</td>
<td style="width: 4.38%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" rowspan="6" width="4%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2;">
<td style="width: 25.54%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="25%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إرسال رسالة خاطئة ” كتابة فقط , رقم أقل من 6 خانات , رسالة فارغة “</span></p>
</td>
<td style="width: 70.08%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="70%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عزيزي المشترك لقد تم إرسال رقم خاطئ يرجى إعادة المحاولة, أرسل الرقم المؤلف من ثمان خانات مسبوقا بالرمز 09&nbsp; اذا كنت تريد حجز رقم خليوي معين او مسبوقا برمز المدينة اذا كنت تريد حجز رقم مشابه لخطك الثابت</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 3;">
<td style="width: 25.54%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="25%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند الموافقة على بيع الرقم سيتم إرسال رسالة متضمنة الرقم الذي تم الموافقة عليه</span></p>
</td>
<td style="width: 70.08%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="70%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عزيزي مشترك </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> تمت الموافقة على طلبكم لشراء الرقم ********09 &nbsp;يرجى زيارة أقرب مركز خدمة مصطحباً معك الهوية الشخصية علماً أن مدة حجز الرقم هي أسبوع واحد كحد أقصى</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 4;">
<td style="width: 25.54%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="25%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند عدم الموافقة على بيع الرقم أو تم حجزه مسبقا</span></p>
</td>
<td style="width: 70.08%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="70%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عزيزي المشترك عذرا الرقم المطلوب 0900000000 غير متوفر</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 5;">
<td style="width: 25.54%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="25%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند عدم الموافقة على بيع رقم مشابه لرقم الهاتف الثابت</span></p>
</td>
<td style="width: 70.08%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="70%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عزيزي المشترك عذرا الرقم المطلوب 0110000000 غير متوفر</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 6; mso-yfti-lastrow: yes;">
<td style="width: 25.54%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="25%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند الموافقة على بيع رقم مشابه لرقم الهاتف الأرضي</span></p>
</td>
<td style="width: 70.08%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="70%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عزيزي مشترك </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> تمت الموافقة على طلبكم لشراء الرقم 0900000000 المشابه لرقم هاتفكم الثابت يرجى زيارة اقرب مركز خدمة مصطحباً معك الهوية الشخصية و آخر فاتورة لخطكم الثابت علما أن مدة حجز الرقم هي أسبوع كحد أقصى</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">معلومات إضافية :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo10; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لا يمكن إرسال رسالة الحجز من أرقام </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Syriatel</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo10; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال تم إرسال رسالة من قبل المشترك متضمنة أكثر من رقم سيتم معالجة أول رقم ضمن الرسالة فقط .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo10; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بحال الاستفسار عن حجز رقم مشابه للخط الثابت يجب مراعاة النقاط التالية : كتابة الرقم بالصيغة الكاملة مع رمز المحافظة ، يجب شراء الخط بنفس اسم مالك الخط الثابت ، يجب إحضار آخر فاتورة للخط الثابت باسمه .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo10; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">أقصى مدة للحصول على الرقم المحجوز هي <b><u>7 أيام</u> </b>، في حال تجاوز هذه المدة يجب على المشترك تقديم طلب جديد .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">بعض تسجيلات الـ </span></b><b><span dir="LTR" lang="EN-GB" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">CRM</span></b><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;"> :</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l4 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">استفسار عن الخدمة</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l4 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">شكوى على الخدمة</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><u><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US; mso-bidi-language: AR-SY;">ملاحظة : لكل حالة تسجيلة خاصة تتماشى مع طبيعة الاستفسار</span></u></b><b><u></u></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
</div>

		
		
			</div><!-- .entry-content .clear -->
</div>
    `,

    image: "linear-gradient(135deg, #4527A0, #4527A0)"
};
