export default {

    //add id to the and replace * with the number of subjects
    // ****** it's important don't igonre it **********
    id: "prepaid-2",

    title: "Prepaid Cancellation",

    content: `
        <div class="WordSection1">
<p class="MsoNormal" dir="RTL" style="text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-size: 14.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إلغاء الاشتراك بالخط المسبق الدفع</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">وصف الخدمة</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن إلغاء الخط المسبق الدفع <b>مباشرةً</b> عبر مراكز الخدمة فقط بأي وقت بغض النظر عن تاريخ تفعيل الخط .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاستفسار عن الخدمة</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">.حضور صاحب العلاقة مع الأوراق الثبوتية المطلوبة </span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2.محاولة معرفة سبب الإلغاء و تقديم البدائل المناسبة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US; mso-bidi-language: AR-SY;">3.إعلام المشترك بضرورة تقديم طلب الإلغاء في مركز </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> رئيسي حصراً</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاشتراك بالخدمة</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 3; mso-yfti-lastrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1.حضور صاحب العلاقة مع الأوراق الثبوتية المطلوبة </span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2.محاولة معرفة سبب الإلغاء و تقديم البدائل المناسبة و محاولة إقناع المشترك بالعدول عن طلبه</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">الأوراق الثبوتية المطلوبة :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الأوراق المطلوبة لإلغاء الاشتراك نفس الأوراق المطلوبة للاشتراك .</span></b></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">حالات خاصة :</span></b></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l1 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">مواطني الجولان :</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l1 level2 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in 1.25in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بطاقة مؤقتة صادرة عن السلطات السورية</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l1 level2 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in 1.25in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال الوفاة : يستطيع مشتركي مواطني الجولان إلغاء الخط في حال وفاة صاحب الخط معتمدين على شهادة الوفاة الصادرة من المشفى .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l1 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الوكالة العامة أو الخاصة :</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l1 level2 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in 1.25in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن قبول الوكالة العامة أو الخاصة مع التأكد من صلاحيتها و <b><u>ذكر صلاحية الموكل حرفياً ضمن الوكالة</u></b> (مثال : إلغاء خط مسبق الدفع) </span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l1 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><b><u><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">ملاحظة :</span></u></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> إذا كانت بيانات المشترك غير مطابقة ، لا يمكن إجراء الإلغاء و يتم توجيه المراجع إلى ضرورة مراجعة صاحب الخط مع الثبوتيات المطلوبة لتنفيذ طلب الإلغاء .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">– </span></b><span lang="AR-SA" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'Times New Roman'; color: black;">يرجى مراجعة صفحة<b> </b></span><span lang="EN-GB"></span><b> </b><span lang="AR-SA" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'Times New Roman'; color: black;">–</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><span lang="EN-GB"></span><b></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">رسم الاشتراك و التعرفة :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">كلفة خدمة الإلغاء <b>مجانية</b> ، <b><u><span style="color: #c00000;">ولكن يخسر المشترك الرصيد الموجود على الخط عند الإلغاء</span></u></b> .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">طريقة الإلغاء :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إذا كانت بيانات المشترك موجودة و متطابقة يتم التأكد من حضور صاحب العلاقة مع بطاقة هويته الشخصية كما أنه لابد من التأكد من وصول العقد إلى الشركة .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يتم تقديم طلب إلغاء خط مسبق الدفع من خلال الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CRM</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></p>
<p class="MsoNormal"><b><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">New Contract – Line Cancellation Request .</span></b><b></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">ثم القيام بنفس الخطوات المتبعة لإلغاء الخط اللاحق الدفع العادي ( ما عدا التصفية ) :</span></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يتم مطابقة رقم الهوية المدرج عبر الباركود بشكل تلقائي مع رقم الهوية الموجود على البرامج و بالتالي من الضروري في حال عدم مطابقة الهوية إجراء تحديث بيانات للمشترك لإتمام العملية .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند إدراج رقم </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">UTS</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ضمن طلب الإلغاء ، ستظهر للموظف الرسالة التالية : </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">“GSM is Prepaid UTS”</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> وبالتالي لن يتمكن من إرسال طلب الإلغاء وفي مثل هذه الحالات من الضروري توجيه المشترك للمتابعة مع الوكيل المعتمد .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">من الضروري تحميل جميع صور الهوية عبر الباركود ( في الخانات الأربعة ) للتمكن من إرسال طلب الإلغاء .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند تقديم طلب الإلغاء ، يتم اختيار ضمن </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Case</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> : </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Prepaid Cancel Line</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> و ضمن الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Specification</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> يتم اختيار سبب الإلغاء :</span></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند الضغط على </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Submit Request</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> يتم تحويل الحالة إلى قسم الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Retention</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بعد الضغط على </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Submit Request</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> سيتم بشكل تلقائي :</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level2 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in 1.0in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إيقاف الخط بطريقة الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Bar in-out</span></b><b> </b></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level2 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in 1.0in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إضافة </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Open Tickler</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> تفيد بتقديم طلب إلغاء الخط :</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 75.32%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="75%">
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin: 0in; margin-bottom: .0001pt; mso-add-space: auto; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span style="mso-bookmark: _Hlk194757369;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Pending LC</span></span></p>
</td>
<td style="width: 24.68%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="24%">
<p class="MsoListParagraphCxSpLast" dir="LTR" style="margin: 0in; margin-bottom: .0001pt; mso-add-space: auto; line-height: normal;"><span style="mso-bookmark: _Hlk194757369;"><b><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Short Description</span></b></span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1; mso-yfti-lastrow: yes;">
<td style="width: 75.32%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="75%">
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin: 0in; margin-bottom: .0001pt; mso-add-space: auto; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span style="mso-bookmark: _Hlk194757369;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">تم تقديم طلب إلغاء الخط في مركز …….. بتاريخ اليوم رقم المتابعة …….</span></span></p>
</td>
<td style="width: 24.68%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="24%">
<p class="MsoListParagraphCxSpLast" dir="LTR" style="margin: 0in; margin-bottom: .0001pt; mso-add-space: auto; line-height: normal;"><span style="mso-bookmark: _Hlk194757369;"><b><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Long Description</span></b></span><b></b></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level2 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in 1.0in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يقوم موظف الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Retention team</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> بإلغاء الخط بشكل كامل في اليوم التالي من تاريخ تقديم طلب الإلغاء .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level2 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in 1.0in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لابد من تنبيه المشترك إلى أنه سيتم خسارة الرصيد عند إلغاء الاشتراك .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال كان إلغاء خط مسبق الدفع لمشترك لديه أكثر من <b><u>5 أرقام</u></b> مسجلة باسمه :</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level2 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in 1.0in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يتم اختيار ضمن الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Case</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> : </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Prepaid Line deactivation for more than 5 lines</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> و ضمن الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Specification</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> يتم اختيار سبب الإلغاء .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level2 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in 1.0in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند الضغط على </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Submit Request</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> يتم إلغاء الخط مباشرة من خلال البرامج (أي يتم تغيير حالة الخط إلى </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> بشكل تلقائي بأسرع وقت ممكن) عندها بإمكان الموظف بيع خط جديد مباشرة .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">معلومات إضافية :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال تراجع المشترك عن طلب إلغاء الخط بنفس يوم تقديم الطلب (قبل أن يصبح الخط </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">) ، فهنا نميز حالتين :</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo8; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخط ضمن فترة الصلاحية أو الاستقبال :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> يتم تقديم طلب تراجع عن إلغاء الخط ليتم تفعيل الخط .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo8; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخط ضمن فترة التجميد :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> يتم تقديم طلب تراجع عن إلغاء الخط <u>و طلب إعادة تفعيل الخط</u> ليتم تفعيل الخط .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال أراد المشترك استعادة الرقم بعد أن يتم إلغاؤه (بعد أن يصبح الخط </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">) ،فبإمكانه ذلك من خلال </span><span lang="EN-GB"></span> <span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">(في حال استيفاء شروط الخدمة) .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال طلب المشترك استرجاع خطه بعد <u>تقديم طلب إلغاء</u> (مشترك لديه أكثر من 5 أرقام) ، يتم توجهيه إلى </span><span lang="EN-GB"></span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> بعد أن يصبح الخط </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> (في حال استيفاء شروط الخدمة)</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لا يمكن حجز الرقم الملغى باسم مشترك آخر إلا بعد مرور سنة على تاريخ تحويل الخط إلى </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">إجراءات قسم الـ </span></b><b><span dir="LTR" lang="EN-GB" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">Retention</span></b><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;"> :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سيقوم قسم الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Retention</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> بمتابعة إلغاء الأرقام التي تقدمت بطلب الإلغاء <u>و بالتالي لا يمكن تقديم طلب التراجع عن الإلغاء في حال طلب المشترك استعادة الرقم لاحقاً</u> .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يقوم قسم الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Retention</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> بتقديم عروض للمشتركين في حال كانت فئة الخط المسبق الدفع المقدم طلب لإلغائه هي من</span> <span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إحدى الشرائح التالية : (</span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Top1 , VHigh , High</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">) بشرط أن يكون معدل الاستهلاك 5,000 ل.س أو أكثر .<s> </s></span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">بعض تسجيلات الـ </span></b><b><span dir="LTR" lang="EN-GB" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">CRM</span></b><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;"> :</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l5 level1 lfo9; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">استفسار عن إلغاء اشتراك خط مسبق الدفع</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l5 level1 lfo9; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">استفسار عن إمكانية استرجاع خط ملغى</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l5 level1 lfo9; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">تحويل طلب لقسم الـ Retention للتراجع عن طلب الإلغاء</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><u><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US; mso-bidi-language: AR-SY;">ملاحظة : لكل حالة تسجيلة خاصة تتماشى مع طبيعة الاستفسار و قد يوجد تسجيلات أخرى صحيحة</span></u></b><b><u></u></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
</div>
    `,

    image: "linear-gradient(135deg, #673AB7, #7E57C2)"

};