export default {

    //add id to the and replace * with the number of subjects
    // ****** it's important don't igonre it **********
    id: "prepaid-4",

    title: "Pick Your Number",

    content: `
        <div class="ast-post-format- single-layout-1">
	
	<div class="entry-content clear" itemprop="text">
		
		<div class="WordSection1">
<p class="MsoNormal" dir="RTL" style="text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-size: 14.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">خدمة اختيار الرقم</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">وصف الخدمة</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">تتيح الخدمة إمكانية اختيار رقم مسبق دفع جديد قبل شراؤه من خلال قائمة الأرقام المتوفرة بالمركز .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاستفسار عن الخدمة</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1.حضور صاحب العلاقة مع الأوراق الثبوتية المطلوبة </span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2.سعر الخط الجديد + كلفة الخدمة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">3.اختيار رقم من الأرقام المتوفرة بالمركز .</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاشتراك بالخدمة</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 3; mso-yfti-lastrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1.حضور صاحب العلاقة مع الأوراق الثبوتية المطلوبة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2.الأسعار و التكاليف</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">3.رموز الحماية </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">PIN-PUK</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">4.إعلام المشترك بمدة تفعيل الخط و طرق التعبئة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">5.شرط صلاحية الخط </span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">6.إعلام المشترك عن العروض المتوفرة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">7.إعلام المشترك بخدمة الصلاحية السنوية و طرح خيار تفعيلها عن طريق الرمز</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">الأوراق الثبوتية المطلوبة :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">نفس الأوراق المطلوبة لدى الاشتراك بالخط المسبق الدفع الجديد .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">رسم الاشتراك و التعرفة :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سعر الخط الجديد بالليرة السورية :</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 47.56%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="47%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">اسم الخدمة</span></b></p>
</td>
<td style="width: 18.66%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="18%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سعر الخدمة</span></b></p>
</td>
<td style="width: 19.74%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="19%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سعر الشريحة</span></b></p>
</td>
<td style="width: 14.02%; border: solid windowtext 1.0pt; border-right: none; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="14%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">المجموع</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1; mso-yfti-lastrow: yes;">
<td style="width: 47.56%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="47%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">اختيار خطوط مسبقة الدفع الجديدة</span></p>
</td>
<td style="width: 18.66%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="18%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2,500</span></p>
</td>
<td style="width: 19.74%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="19%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">45,000</span></p>
</td>
<td style="width: 14.02%; border-top: none; border-left: solid windowtext 1.0pt; border-bottom: solid windowtext 1.0pt; border-right: none; mso-border-top-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" width="14%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">47,500</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">طريقة بيع الخط :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يتم البيع من خلال برنامج الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CRM</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> : </span></p>
<p class="MsoListParagraphCxSpMiddle"><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Reports – Line Reservation </span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">ومن ثم اختيار </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">GSM List For Sale</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ، حيث يمكن طباعة قائمة الأرقام للمشترك كما هو متبع بالخطوط اللاحقة الدفع لاختيار الرقم الذي يرغب بشرائه .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">و بعد اختيار الرقم المراد شراؤه يتم الضغط على </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Sell GSM Pre</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سيتم الدخول إلى صفحة بيع الرقم المسبق الدفع الجديد و تعبئة البيانات المطلوبة بالطريقة المعتادة مع اختيار نوع الخط </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Pick Your Pre</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> و يظهر الرقم الخليوي الذي تم اختياره كما يلي :</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بعد تعبئة البيانات المطلوبة و البصمة و الهوية كما هو معتاد ، يتم الضغط على حفظ ، فيظهر كما موضح أدناه :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">و تظهر صورة العقد :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">و يظهر الإيصال كما يلي :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo2; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">و يتم تلقائياً تسجيل حالة على الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CRM </span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-spacerun: yes;">&nbsp;</span>:</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">ثم يظهر الخط على البرامج كأي خط مسبق دفع عادي و يخضع لدورة حياة الخط المسبق الدفع الجديد (صلاحية 90 يوم) بمجرد تفعيل الخط .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">معلومات إضافية :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l2 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخدمة متوفرة ضمن مراكز الخدمة فقط .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l2 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لدى شراء الخط من المركز يجب إجراء التعبئة الأولى مباشرة في مركز الخدمة ، علماً أن الخط سيخضع لدورة حياة الخط المسبق الدفع المعتادة .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l2 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يعامل الخط كخط مسبق دفع عادي من حيث (شروط الاشتراك و العقد ، الأوراق الثبوتية ، الأسعار ، نظام الخط المسبق و دورة حياة الخط ، الاشتراك بالخدمات ، …..)</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l2 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">من الممكن أن تتم التعبئة الأولى بأي قيمة كانت .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l2 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">5.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">نوع الخط الذي يمكن الحصول عليه هو خط مسبق دفع عادي ، أي لا يمكن اختيار نوع الخط شباب أو ثواني ، ولكن يمكن للمشترك في حال رغبته إجراء إعادة تحويل الخط إلى شباب أو ثواني أو لاحق الدفع بالطرق المعتادة .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l2 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">6.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سيتم تفعيل الخط خلال ساعتين .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l2 level1 lfo5; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">7.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">بإمكان المشترك إجراء تغيير للرقم بالطريقة المعتادة .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">بعض تسجيلات الـ </span></b><b><span dir="LTR" lang="EN-GB" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">CRM</span></b><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;"> :</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l1 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">استفسار عن الخدمة</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><u><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US; mso-bidi-language: AR-SY;">ملاحظة : لكل حالة تسجيلة خاصة تتماشى مع طبيعة الاستفسار</span></u></b><b><u></u></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></b></p>
</div>

		
		
			</div><!-- .entry-content .clear -->
</div>
    `,

    image: "linear-gradient(135deg, #673AB7, #7E57C2)"

};