export default {
    id: "prepaid-51",
    title: "Shabab lines",
    // excerpt: "Multiple ways to add credit to your prepaid account and avoid service interruption.",
    content: `<div class="WordSection1">
<p class="MsoNormal" dir="RTL" style="direction: rtl;line-height: 115%;text-align: right"><b><span dir="LTR" style="font-size: 18.0pt;line-height: 115%;font-family: 'Times New Roman',serif">خط الشباب</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">خط شباب هو خط مسبق دفع يحتوي على 450 ل.س رصيد و اشتراك مجاني دائم&nbsp;بخدمة السوبر كليب.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تقسم ال 450 ل.س الى قسمين : </span></b></p>
<ul type="disc">
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;line-height: 115%;direction: rtl"><b><u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">337.5&nbsp;ل.س رصيد أساسي :</span></u></b><u></u></li>
</ul>
<p class="MsoNormal" dir="RTL" style="margin-right: .25in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مخصص لإجراء الاتصالات الخلوية المحلية والدولية و الشبكة الثابتة&nbsp;و إرسال الرسائل الدولية.</span></p>
<ul type="disc">
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;line-height: 115%;direction: rtl"><b><u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">112.5 ل.س رصيد باقة شباب صالحة لمدة 45 يوم: </span></u></b><u></u></li>
</ul>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تتضمن ما يلي :</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .75in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">باقة الرسائل القصيرة تتضمن ( 110 رسالة محلية قصيرة )</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .75in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">باقة الانترنت تتضمن ( 5 ميغا بايت انترنت )</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم الحصول على الباقة عند :</span></b></p>
<ul type="disc">
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;تفعيل خط شباب جديد</span></li>
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">إعادة التعبئة بفئة&nbsp; 450 أو 225 أو 1000 ل.س</span></li>
</ul>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لمعرفة </span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">فئات التعبئة الـخاصة بخط شباب</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SY" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">في </span></b><b><span lang="AR-SA" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">حال الاستفسار عن خدمة ال </span></b><b><span dir="LTR" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN Shabab</span></b><b><span lang="AR-SY" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">:</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">هو خط مسبق دفع يتضمن باقة شباب ولديه اشتراك دائم بخدمة السوبر كليب.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">فئات التعبئة ورصيد باقة شباب ضمنها.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تكاليف الاتصال. </span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">طريقة تحويل الخط لشباب وشروط التحويل. </span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">طريقة الاستعلام عن الرصيد.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl">
</p><p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 18.0pt;line-height: 115%;font-family: 'Times New Roman',serif">رسم الاشتراك و التعرفة:</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لا يوجد اشتراك شهري للخدمة</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تكلفة الاتصال مع التخفيض :</span></p>
<div align="right">
<table class="MsoTable15Grid1Light" dir="rtl" style="width: 495.45pt;border-collapse: collapse;border: none" border="1" width="661" cellspacing="0" cellpadding="0" align="right">
<tbody>
<tr style="height: .5in">
<td style="width: 123.0pt;border: solid #999999 1.0pt;padding: 0in 5.4pt 0in 5.4pt;height: .5in" rowspan="3" width="164">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">جهة الاتصال/ التكلفة حسب التوقيت</span></b></p>
</td>
<td style="width: 62.0pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="83">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Zone 1</span></b><b></b></p>
</td>
<td style="width: 58.5pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="78">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Zone 2</span></b><b></b></p>
</td>
<td style="width: .75in;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="72">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Zone 3</span></b><b></b></p>
</td>
<td style="width: 63.0pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Zone 4</span></b><b></b></p>
</td>
<td style="width: 63.0pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Zone</span></b><b> </b><b><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">5</span></b><b></b></p>
</td>
<td style="width: 71.95pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="96">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Zone</span></b><b> </b><b><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">6</span></b><b></b></p>
</td>
</tr>
<tr style="height: 60.85pt">
<td style="width: 62.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 60.85pt" width="83">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Peak time</span></p>
</td>
<td style="width: 58.5pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 60.85pt" width="78">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Off-Peak time 1</span></p>
</td>
<td style="width: .75in;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 60.85pt" width="72">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Off-Peak time 2</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 60.85pt" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Off-Peak time 3</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 60.85pt" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Off-Peak time</span> <span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">4</span></p>
</td>
<td style="width: 71.95pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 60.85pt" width="96">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Happy Friday</span></p>
</td>
</tr>
<tr style="height: .5in">
<td style="width: 62.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="83">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">09:00 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">à</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
21:59 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">pm</span></p>
</td>
<td style="width: 58.5pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="78">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">22:00 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">pm</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">à</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
</span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">23</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">:59 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">pm</span></p>
</td>
<td style="width: .75in;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="72">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">00:00 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">à</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
00:59 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">0</span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">:00 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">à</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
0</span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">5</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">:59 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">0</span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">6</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">:00 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">à</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
0</span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">8</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">:59 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span></p>
</td>
<td style="width: 71.95pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: .5in" width="96">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">0</span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">6</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">:00 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">am</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">à</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"><br>
17:59 </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">pm</span></p>
</td>
</tr>
<tr style="height: 68.15pt">
<td style="width: 123.0pt;border: solid #999999 1.0pt;border-top: none;padding: 0in 5.4pt 0in 5.4pt;height: 68.15pt" width="164">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">دقيقة الاتصال و التحويل الى خليوي محلي</span></b></p>
</td>
<td style="width: 62.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 68.15pt" width="83">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">63</span></p>
</td>
<td style="width: 58.5pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 68.15pt" width="78">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">63</span></p>
</td>
<td style="width: .75in;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 68.15pt" width="72">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">30</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 68.15pt" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">30</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 68.15pt" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">30</span></p>
</td>
<td style="width: 71.95pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 68.15pt" width="96">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">30</span></p>
</td>
</tr>
<tr style="height: 89.75pt">
<td style="width: 123.0pt;border: solid #999999 1.0pt;border-top: none;padding: 0in 5.4pt 0in 5.4pt;height: 89.75pt" width="164">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">دقيقة الاتصال الى ارضي + التحويل من خط مسبق الدفع شباب</span></b></p>
</td>
<td style="width: 62.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 89.75pt" width="83">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">58</span></p>
</td>
<td style="width: 58.5pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 89.75pt" width="78">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">58</span></p>
</td>
<td style="width: .75in;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 89.75pt" width="72">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">46</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 89.75pt" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">46</span></p>
</td>
<td style="width: 63.0pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 89.75pt" width="84">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">46</span></p>
</td>
<td style="width: 71.95pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 89.75pt" width="96">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">46</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تكلفة استخدام الإنترنت بعد انتهاء الرصيد الأساسي تكون بالتكلفة العادية.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">كلفة الرسالة الدولية: 1200 ل.س.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">كلفة الرسالة المحلية: 5 ل.س.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">كلفة الاتصال الدولي بنفس التكلفة المعتادة&nbsp; للخط المسبق الدفع.</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">7.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">كلفة الاتصال من خط شباب بخدمة المشتركين 111هي 30 ل.س.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">طريقة تحويل الخط :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">إمكانية التحويل من خط شباب إلى خط مسبق دفع عادي و بالعكس عبر خدمة دليلي </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">*111#</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تحويل الخط المسبق الدفع العادي إلى خط </span></u><u><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span></u><u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> شباب</span></u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> :</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مجاناً بشرط توفر 450&nbsp;أو 225 أو 1000 ل.س في رصيد المشترك وعندها سيحصل على رصيد باقة شباب و سوبر كليب</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">_يظهر تحويل الخط المسبق الدفع إلى خط شباب في برنامج الـ&nbsp;</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">CRM</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> ضمن خانة Conversion History على الشكل التالي:</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><img decoding="async" class="alignnone wp-image-64229 size-full" src="http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/1-1.png" alt="" width="474" height="160" srcset="http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/1-1.png 474w, http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/1-1-300x101.png 300w" sizes="(max-width: 474px) 100vw, 474px"></p>
<p dir="RTL">
</p><p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تحويل خط </span></u><u><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span></u><u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> شباب إلى خط مسبق الدفع عادي:</span></u></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">بتكلفة 150 ل.س بشرط أن يكون قد مر45 يوم على تاريخ الاتصال الأول عندها سيتم إلغاء خدمة السوبر كليب و تستمر الاستفادة من&nbsp; باقة الانترنت والرسائل القصيرة.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">_يظهر تحويل خط شباب إلى الخط المسبق الدفع في برنامج الـ</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">INAPI</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> على الشكل التالي:</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><img decoding="async" loading="lazy" class="alignnone wp-image-64230 size-full" src="http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/2.gif" alt="" width="654" height="70"></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 18.0pt;line-height: 115%;font-family: 'Times New Roman',serif">شروط التحويل :</span></b></p>
<ul type="disc">
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;line-height: 115%;direction: rtl"><u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">عند تحويل الخط من شباب إلى مسبق الدفع عادي</span></u><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> وأراد المشترك إعادته إلى الحالة السابقة &nbsp;“من عادي إلى شباب” &nbsp;ضمن نفس اليوم أي خلال الـ 24 ساعة لا يتم تنفيذ الطلب و ستظهر الرسالة التالية:</span></li>
</ul>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl">
</p><ul type="disc">
<li class="MsoNormal" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;&nbsp; <u>عند طلب تحويل الخط من شباب إلى مسبق الدفع عادي</u> يجب أن يكون الخط قد مضى عليه 45 يوم كخط شباب&nbsp;ليتم التحويل وفي حال المحاولة قبل مرور المدة اللازمة &nbsp;ستظهر الرسالة التالية:</span></li>
</ul>
<p class="MsoNormal" dir="RTL" style="margin-right: .25in;text-align: justify;line-height: 115%;direction: rtl">
</p><p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 18.0pt;line-height: 115%;font-family: 'Times New Roman',serif">قائمة تحويل الخ</span></b><b><span lang="AR-SY" style="font-size: 18.0pt;line-height: 115%;font-family: 'Times New Roman',serif">ط :</span></b><b> </b></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">عبر قائمة دليلي #111* :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">10) تحويل الخط :</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">إلى </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> ثواني</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">إلى </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> دقائق</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">إلى </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> شباب </span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">التحويل بين الخطوط يتم عن طريق الرمز </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">*111#</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> مجاناً</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">، شرط الحفاظ على الشروط الموضحة أدناه :</span></p>
<div align="right">
<table class="MsoTable15Grid1Light" dir="rtl" style="width: 446.55pt;border-collapse: collapse;border: none" border="1" width="595" cellspacing="0" cellpadding="0">
<tbody>
<tr style="height: 25.15pt">
<td style="width: 81.5pt;border: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;padding: 0in 5.4pt 0in 5.4pt;height: 25.15pt" width="109">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Current / New</span></b><b></b></p>
</td>
<td style="width: 108.6pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 25.15pt" width="145">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">التعرفة بالثواني</span></b><b></b></p>
</td>
<td style="width: 121.5pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 25.15pt" width="162">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">التعرفة العادية (الدقائق)</span></b><b></b></p>
</td>
<td style="width: 134.95pt;border-top: solid #999999 1.0pt;border-left: solid #999999 1.0pt;border-bottom: solid #666666 1.5pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 25.15pt" width="180">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">خط الشباب</span></b><b></b></p>
</td>
</tr>
<tr style="height: 77.25pt">
<td style="width: 81.5pt;border: solid #999999 1.0pt;border-top: none;padding: 0in 5.4pt 0in 5.4pt;height: 77.25pt" width="109">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">التعرفة بالثواني</span></b><b></b></p>
</td>
<td style="width: 108.6pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 77.25pt" width="145">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">X</span></b></p>
</td>
<td style="width: 121.5pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 77.25pt" width="162">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مدة الاشتراك بالعرض اكبر أو تساوي 30 يوم / مجانية</span></p>
</td>
<td style="width: 134.95pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 77.25pt" width="180">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">توفر 225 أو 450 او 1000ل.س، ومدة الاشتراك بالعرض اكبر أو تساوي 30 يوم</span></p>
</td>
</tr>
<tr style="height: 75.55pt">
<td style="width: 81.5pt;border: solid #999999 1.0pt;border-top: none;padding: 0in 5.4pt 0in 5.4pt;height: 75.55pt" width="109">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">التعرفة العادية (الدقائق)</span></b><b></b></p>
</td>
<td style="width: 108.6pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 75.55pt" width="145">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">ان تكون مدة الاشتراك اكبر او تساوي 30 يوم /عملية التحويل مجانية</span></p>
</td>
<td style="width: 121.5pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 75.55pt" width="162">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">X</span></b></p>
</td>
<td style="width: 134.95pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 75.55pt" width="180">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">توفر 225 أو 450 او 1000ل.س</span></p>
</td>
</tr>
<tr style="height: 84.55pt">
<td style="width: 81.5pt;border: solid #999999 1.0pt;border-top: none;padding: 0in 5.4pt 0in 5.4pt;height: 84.55pt" width="109">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">خط الشباب</span></b><b></b></p>
</td>
<td style="width: 108.6pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 84.55pt" width="145">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مرور 45 يوم على كون الخط شباب و إلغاء الخدمات الخاصة بخط شباب و كلفة التحويل 150 ل.س</span></p>
</td>
<td style="width: 121.5pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 84.55pt" width="162">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مرور 45 يوم على كون الخط شباب و إلغاء الخدمات الخاصة بخط شباب و كلفة التحويل 150 ل.س</span></p>
</td>
<td style="width: 134.95pt;border-top: none;border-left: solid #999999 1.0pt;border-bottom: solid #999999 1.0pt;border-right: none;padding: 0in 5.4pt 0in 5.4pt;height: 84.55pt" width="180">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt;text-align: center;line-height: 115%;direction: rtl" align="center"><b><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">X</span></b></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoListParagraph" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">من مسبق الدفع إلى شباب :&nbsp;&nbsp; </span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تظهر العبارة التالية: </span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">“</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يجب توفر 225 ل.س على الأقل في رصيدكم”</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1 موافق ، 2 إلغاء</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">في حال وجود رصيد أكبر أو يساوي 450 ل.س على الخط المسبق الدفع العادي المراد تحويله لخط </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> شباب سيظهر للمشترك الخيارات التالية في قائمة التحويل:</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">“أرسل 1 للتحويل باستخدام&nbsp; 450 ل.س أو 2 للتحويل بـ 225 ل.س او 3 للتحويل بـ1000 ل.س”</span></p>
<p class="MsoListParagraph" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><b><span style="font-size: 14.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b><!--[endif]--><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مثال 1:</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مشترك الخط&nbsp;المسبق العادي لديه 1000 ل.س يود تحويل خطه إلى شباب سيصبح مايلي :</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم تقسيم 1000 كالتالي&nbsp;: يتم التحويل باستخدام 450 ل.س</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">887.5 ل.س رصيد أساسي ( 337.5+ 550 رصيد سابق ) و112.5 ل.س رصيد باقة 45 يوم صلاحية.</span></p>
<p class="MsoListParagraph" dir="RTL" style="margin-right: .75in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><b><span style="font-size: 14.0pt;line-height: 115%;font-family: Symbol">·<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b><!--[endif]--><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مثال 2:</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مشترك الخط&nbsp; المسبق العادي لديه 500 ل.س يود تحويل خطه إلى شباب سيصبح مايلي :</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم تقسيم 500 كالتالي&nbsp; : يتم التحويل باستخدام 225 ل.س.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">443.75 ل.س رصيد أساسي ( 168.75+ 275 رصيد سابق&nbsp;&nbsp; ) و 56.25 ل.س رصيد باقة 30 يوم صلاحية</span></p>
<p class="MsoListParagraph" dir="RTL" style="margin-right: .5in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">من شباب إلى مسبق الدفع :</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تظهر العبارة التالية : “التكلفة 150 ل.س إذا كان الخط شباب”</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1 موافق ، 2 إلغاء</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">الرسائل الخاصة بقائمة *111 # &nbsp;لإجراء عمليات التحويل</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لمعرفة&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 18.0pt;line-height: 115%;font-family: 'Times New Roman',serif">ملاحظات : </span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لا يمكن تحويل الخط أثناء مرحلة الاستقبال أو التجميد.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">سيتم إيقاف خدمة السوبر كليب و الاحتفاظ بباقة الانترنت و الرسائل القصيرة.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لا يوجد عدد محدد من المرات المسموح بتحويل الخط من مسبق عادي إلى خط شباب مع مراعاة الشروط الواجب توفرها.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم تنفيذ طلب تحويل الخط من مسبق عادي إلى شباب و بالعكس&nbsp; مباشرة على النظام , و بالنسبة لتفعيل خدمة السوبر كليب&nbsp; تحتاج إلى ساعة كونها لا تخضع للوقت الافتراضي لتفعيل الخدمات باعتبار انه يتم تفعيلهم كباقة خدمات متكاملة.</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="margin-right: .25in;margin-left: 0in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لا تتأثر خدمة دقة و غنية في حال وجودها على الخط لدى إجراء تحويل الخط من مسبق دفع عادي إلى شباب أو بالعكس.</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 18.0pt;line-height: 115%;font-family: 'Times New Roman',serif">معلومات إضافية :</span></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">1.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم تفعيل خط </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> شباب عن طريق إجراء أي اتصال و يتم بعدها استلام رسالة نصية باللغة العربية متضمنة الرقم الخليوي من المرسل </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> نص الرسالة : “عزيزي مشترك </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> &nbsp;إن رقمكم هو </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">963*********</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">“</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">ثم تصل رسالة تؤكد تفعيل خدمة السوبر كليب</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">2.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يخضع خط شباب&nbsp; لنفس شروط وصول البيانات و تفعيل الخط المسبق الدفع العادي.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">3.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">كل باقة لخط شباب منفصلة من حيث الرصيد والصلاحية الخاص بها</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">4.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">أولوية الخصم عند تعبئة عدة باقات هي للباقة الاقرب انتهاء صلاحية</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">مثال : خط لديه باقة شباب 450 تحتوي رسائل قصيرة 5 رسائل و انترنت 2</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MB</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> و المتبقي من صلاحيتها 35 يوم , عند تعبئة الخط بفئة 225 شباب ينتقل استهلاك الانترنت و الرسائل المحلية ليصبح من باقة 225 و ذلك لان انتهاء صلاحيتها اقرب من انتهاء صلاحية باقة ال 450</span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">5.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يخضع خط شباب لجميع مراحل الخطوط المسبقة الدفع (90 يوم صلاحية, استقبال, تجميد وإعادة تفعيل ….. )</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">6.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">عند وجود باقات رسائل او انترنت ( باقات شهرية – باقات يلا ….الخ )على الخط و تعبئة الخط ب</span><span lang="AR-SY" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">أ</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">ي من باقات الشباب المتوفرة ستكون أولوية الاستهلاك من الباقات الموجودة وبعد&nbsp; انتهائها ينتقل الاستهلاك ليصبح من باقات شباب</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">7.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يمكن تعبئة الخط بجميع الفئات تماماً كالخط المسبق الدفع العادي.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">8.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لدى تعبئة خط شباب بأي فئة من الفئات المتوفرة ماعدا الـ 225 أو 450 أو 1000ل.س سيتم إضافة قيمة البطاقة للرصيد الأساسي و لن يتأثر رصيد الباقة.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">9.<span style="font: 7.0pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">فئتي 450 و 225 ل.س خاصة بخط شباب فقط و بحال محاولة تحويلها إلى خط عادي ستظهر رسالة تدل على عدم إمكانية التحويل لان الخط ليس شباب في صفحة التحويل على الـ </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">CRM</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">، وذلك لدى التحويل عبر مراكز الخدمة </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">MTN</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">10. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يمكن تعبئة فئة الـ 1000 ل.س على الخط العادي و خط شباب، عند التعبئة لخط عادي يحصل المشترك على 959 ل.س ، وعند التعبئة لخط شباب سيتم تقسيم الرصيد الى رصيد اساسي و رصيد باقات.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">11. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم الاستعلام عن الرصيد الأساسي عن طريق الرمز #100*</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">12. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم الاستعلام عن رصيد باقات شباب من خيار باقاتي ضمن #111* حيث سيصل للمشترك الرسالة التالية : “باقي لديك __ (ميغا أو رسالة)&nbsp; لغاية –/–/—- “</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">13. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تفقد رصيد باقات الشباب يتم عبر نافذة </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">Usage Counter</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;:</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><img decoding="async" loading="lazy" class="alignnone size-full wp-image-64231" src="http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/3-2.png" alt="" width="295" height="208"></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">14. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">عند انتهاء رصيد باقة الانترنت شباب ستصل رسالة نصية :<strong>نفذ رصيد الانترنت أصبح الميغا ب 27 ل.س.</strong></span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">وعند انتهاء رصيد باقة الرسائل تصل رسالة<b>: نفذ رصيد الرسائل التكلفة 5 ل.س </b></span><sup>[pre3]</sup></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">15. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">عند انهاء جلسة الانترنت&nbsp; ستظهر رسالة : استهلكت أقل من 100% من باقة شباب</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">16. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">عند ارسال رسالة من باقة شباب ستظهر رسالة :&nbsp; استهلكت رسالة من باقة الشباب —</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">17. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لا يتم خسارة رصيد باقة شباب إلا في حال انتهاء صلاحية الباقة أو إلغاء الخط.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">18. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">الحد الأعلى للرصيد الأساسي هو مليونين ل.س</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">19. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لا يمكن تعبئة اي فئة عند الوصول للحد الأعلى للرصيد الأساسي.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">20. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">خط شباب مشابه تماما للخط المسبق الدفع العادي من حيث الاشتراك بالخدمات , تغير اللغة عبر 1819 , إيقاف الخط بسبب الضياع و استخدام الخط أثناء التجوال، و يختلف عن الخط العادي بالباقة المقدمة عند تعبئة 225 أو الـ 450 ل.س و خدمة تحويل الليرات، إضافة إلى تكلفة الاتصال إلى خليوي أو أرضي و ميزات باقة شباب و الاشتراك المجاني بخدمة السوبر كليب.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">21. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يمنح مشترك خط شباب اشتراك شهري مجاني بخدمة السوبر كليب و يستمر هذا الاشتراك على الخط بغض النظر عن حالة الخط أي عند إعادة تفعيل الخط ستتفعل خدمة سوبر كليب تلقائيا و مجاناً. علماً أنه لن تصل رسائل تذكير بتجديد الخدمة.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">22. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يمكن تحويل خط شباب إلى خط لاحق دفع بنفس الطريقة والكلفة في الخط المسبق الدفع العادي.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">23. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">لا يمكن تحويل الخط اللاحق الدفع لخط شباب حتى وإن كان سابقا خط مسبق دفع بل عليه تحويل الخط إلى مسبق دفع عادي و من ثم تحويله إلى خط شباب.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">24. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يمكن تمييز خط شباب من برنامج الـ </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">CRM</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> من خلال بند </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">service Class</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> حيث تظهر على الشكل التالي :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><img decoding="async" loading="lazy" class="alignnone wp-image-64232 size-full" src="http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/4-2.png" alt="" width="404" height="98" srcset="http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/4-2.png 404w, http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/4-2-300x73.png 300w" sizes="(max-width: 404px) 100vw, 404px"></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">25. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يمكن تحويل الليرات إرسال و استقبال ضمن خطوط شباب فقط أي لا يمكن إرسال أو استقبال ليرات من و إلى خط مسبق دفع عادي.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">26. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">في حال اتصال خط شباب بالرقم 1810 لتحويل رصيد سيتم فصل الاتصال من دون احتساب أي تكلفة ، و في حال تم استخدام طريقة الرسائل 1810 سيفشل الإرسال.</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .5in;text-align: justify;text-indent: -.25in;line-height: 115%;direction: rtl"><!-- [if !supportLists]--><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">27. </span><!--[endif]--><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يظهر الاشتراك بباقات شباب من صفحة </span><span dir="LTR" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">GSM Offer</span><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif"> :</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><img decoding="async" loading="lazy" class="alignnone size-full wp-image-64233" src="http://10.10.89.37/CC_Web_tool/wp-content/uploads/2015/01/5-1.png" alt="" width="293" height="190"></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">للاطلاع على طريقة تحويل الليرات ضمن خطوط الشباب <a href="http://10.10.89.37/cc_web_tool/?p=64182"><span style="color: #4472c4">اضغط هنا</span></a></span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 16.0pt;line-height: 115%;font-family: 'Times New Roman',serif">تفعيل الخدمة :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم بيع الخط بنفس الطريقة المتبعة لبيع الخطوط المسبقة الدفع العادية</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><b><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">الغاء الخدمة :</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: justify;line-height: 115%;direction: rtl"><span lang="AR-SA" style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">يتم بنفس الطريقة المتبعة في الخطوط المسبقة الدفع العادية</span></p>
<p class="MsoNormal" style="text-align: justify;line-height: 115%"><span style="font-size: 14.0pt;line-height: 115%;font-family: 'Times New Roman',serif">&nbsp;</span></p>
</div>`,


    // date: "Jun 15, 2023",
    image: "linear-gradient(135deg, #673AB7, #7E57C2)"
};