export default {

    //add id to the and replace * with the number of subjects
    // ****** it's important don't igonre it **********
    id: "prepaid-3",

    title: "Stay With Us",

    content: `
        <div class="WordSection1">
<p class="MsoNormal" dir="RTL" style="text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-size: 14.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">خدمة خليك معنا – </span></b><b><span dir="LTR" lang="EN-GB" style="font-size: 14.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Stay With Us</span></b><b></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">وصف الخدمة</span></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">تتيح الخدمة لمشتركين الخطوط المسبقة الدفع الذين تم إلغاء خطوطهم (سواء بشكل تلقائي أو من خلال تقديم طلب) بإعادة تفعيل الخط عبر مراجعة مركز خدمة أو الوكلاء أو الموزعين المعتمدين .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<div align="right">
<table class="MsoTableGrid" dir="rtl" style="width: 100.0%; border-collapse: collapse; border: none; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-table-dir: bidi;" border="1" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاستفسار عن الخدمة</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1.حضور صاحب العلاقة مع الأوراق الثبوتية المطلوبة </span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2.كلفة إعادة تفعيل الخط</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">3.التأكد من تحقيق شرط الخدمة (أن يكون الخط قد أجرى آخر استهلاك من الخط خلال فترة لم تتجاوز الـ 6 أشهر أي 180 يوم) .</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: center; line-height: normal; direction: rtl; unicode-bidi: embed;" align="center"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">المعلومات الأساسية المطلوب تزويدها للمشترك في حال الاشتراك بالخدمة</span></b></p>
</td>
</tr>
<tr style="mso-yfti-irow: 3; mso-yfti-lastrow: yes;">
<td style="width: 100.0%; border: solid windowtext 1.0pt; border-top: none; mso-border-top-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt; padding: 0in 5.4pt 0in 5.4pt;" valign="top" width="100%">
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">1.حضور صاحب العلاقة حصراً مع الوثائق الثبوتية المطلوبة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">2.كلفة إعادة تفعيل الخدمة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">3.شرح شروط الخدمة</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">4.رموز الحماية (</span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">PIN – PUK</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">)</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">5.التأكيد على المشترك أن الخط لا يحوي الرصيد السابق قبل إلغاء الخط ، أي أنه سيخسر الرصيد السابق .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">6.إعلام المشترك بمدة التفعيل و طرق التعبئة .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">7.إعلام المشترك عن خدمة الصلاحية السنوية و طرح خيار تفعيلها .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #c00000; mso-bidi-language: AR-SY;">ملاحظة يجب <u>عدم</u> إعلامها للمشترك :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #c00000; mso-bidi-language: AR-SY;"> لكي يتمكن المشترك من الاستفادة من خدمة خليك معنا يجب أن تكون حالة الخط </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; color: #c00000; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #c00000; mso-bidi-language: AR-SY;"> لمدة <b><u>لا</u></b> تتجاوز الـ 55 يوماً .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-bottom: .0001pt; text-align: right; line-height: normal; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; color: #c00000; mso-bidi-language: AR-SY;">(<b>90</b> يوم صلاحية من آخر استهلاك + <b>5</b> أيام استقبال + <b>30</b> يوم تجميد + <b>55</b> يوم الخط ملغى = <b>180</b> يوم)</span></p>
</td>
</tr>
</tbody>
</table>
</div>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">شروط الاشتراك :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l5 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">أن يكون الخط قد أجرى آخر استهلاك من الخط منذ فترة لم تتجاوز 6 أشهر .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l5 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">حضور صاحب الخط إلى مركز الخدمة أو الموزع المعتمد مع الأوراق الثبوتية المقبولة ، و التي هي نفس الأوراق الثبوتية للاشتراك بخط مسبق دفع جديد .</span></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .25in; text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><span lang="EN-GB"></span><b></b></p>
<p class="MsoNormal" dir="RTL" style="margin-right: .25in; text-align: center; direction: rtl; unicode-bidi: embed;" align="center"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">رسم الاشتراك والتعرفة :</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l5 level1 lfo3; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">–<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">كلفة الشريحة الجديدة : <b>45,000 ل.س</b></span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">طريقة إعادة التفعيل :</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يتم الدخول إلى برنامج الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CRM</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ضمن : </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">New Contract – Reactivate Prepaid Line</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال كان الخط قد أجرى آخر استهلاك منذ فترة تجاوزت 6 أشهر ، أي أن حالة الخط </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> منذ أكثر من 55 يوم :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">في حال كان يمكن إعادة تفعيل الخط ، نجد في الصفحة التالية التي توضح الاسم الثلاثي للمشترك مع رقم الوثيقة الثبوتية ( هوية أو جواز سفر ) :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">عند الضغط على ( </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Continue</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ) سينتقل للصفحة الخاصة بتعبئة البيانات :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">5.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">ثم تظهر صورة العقد :</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">6.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">تظهر الحالة ضمن </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">History</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> الخط ، كما هو موضح أدناه :</span></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">7.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">المدة اللازمة لإعادة تفعيل الخط مع تغيير الشريحة <b><u>حوالي ساعتين</u></b> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l8 level1 lfo6; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">8.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">رسائل الأخطاء المتعلقة بالخدمة :</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الرقم خاطئ : </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">GSM is not valid</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">رقم مسبق دفع فعال : </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">GSM is active</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">3)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الرقم ليس مسبق دفع : </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">GSM is not Prepaid</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">4)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">رسالة تتعلق بحالة تقنية على الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Billing System</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> : </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">GSM is not available</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level1 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in .75in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">5)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">رسائل تتعلق بحالة الخط ضمن الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Billing System</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level2 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in 1.25in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">a.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Contract is active</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level2 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in 1.25in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">b.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Contract is suspended</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l0 level2 lfo7; direction: rtl; unicode-bidi: embed; margin: 0in 1.25in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">c.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Contract is on-hold</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">ملاحظة :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> بالنسبة للحالات (4 و 5) يجب تحويل الحالة إلى قسم الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">BO</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ، وذلك بعد التأكد من أن الخط ملغى على برنامج الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">IN</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> (</span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">inapi</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">) ، لكي يتم تحويل حالة الخط إلى </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ، وعندها يصبح المشترك قادر على الاستفادة من الخدمة .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">معلومات إضافية :</span></b></p>
<p class="MsoListParagraphCxSpFirst" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخدمة متوفرة ضمن مراكز </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">MTN</span> <span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الرئيسية و الوكلاء و الموزعين المعتمدين .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لدى إعادة تفعيل الخط في المركز بإمكان المشترك عدم إجراء التعبئة الأولى مباشرة في مركز الخدمة حيث بمجرد تم تفعيل الخط سيتمكن المشترك من إجراء التعبئة بأي طريقة من الطرق المعتادة (موزع ، تحويل ليرات عن طريق المركز ، تحويل ليرات من مشترك آخر ….)</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">التعبئة الأولى ستتم بعد إتمام عملية إعادة تفعيل الخط .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن الاستفادة من هذه الخدمة عدد غير محدد من المرات .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">5.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">تشمل هذه الخدمة الخطوط مسبقة الدفع (عادي – شباب – ثواني) ، علماً أن أي نوع من هذه الخطوط سيصبح خط مسبق دفع عادي من بعد عملية إعادة التفعيل .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">6.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">سيخسر المشترك كامل الرصيد الذي كان متوفر على خطه قبل إعادة التفعيل .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">7.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">ستتم المحافظة على إمكانية إعادة تفعيل الخط بالطريقة العادية التي يمكن إجراؤها قبل انتهاء فترة التعليق .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">8.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">الخدمات التي سوف تتوفر على الخط بعد إعادة تفعيله هي نفس الخدمات التي تتفعل مع الخط الجديد .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">9.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لن تبقى بيانات المشترك متوفرة على برنامج </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CRM</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> حيث سيتم حذف الرقم من </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">IN</span></b> <span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">و </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">HLR</span></b> <span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">،&nbsp;بينما يتم الاحتفاظ بالبيانات من قبل قسم </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Billing</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> (خلال المدة المحددة للاستفادة من خدمة خليك معنا ) .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">10. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لا يوجد أي ضرورة لتوفر الشريحة القديمة مع المشترك عند إعادة تفعيل الخط .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">11. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">إن الخطوط المسبقة الدفع بعد فترة التجميد و بعد أن تصبح حالة الخط (</span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">) تبقى باسم صاحب الخط <u>لمدة 55 يوم</u> , و بعد هذه المدة يمكن للمشترك استعادة الرقم عن طريق مركز الخدمة عبر &nbsp;الرابط <span style="mso-spacerun: yes;">&nbsp;</span></span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">أو عن طريق الموزعين المعتمدين أو عن طريق الوكلاء وستتم متابعة الأرقام من قبل قسم المبيعات و إرسال رسالة للمشترك تعلمه بإمكانية الحصول على الرقم .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">12. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">مع العلم أنه لا يمكن حجز الرقم باسم مشترك آخر إلا بعد <b><u>مرور سنة</u></b> على تاريخ تحويل الخط إلى </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">13. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لا يمكن للمشترك الذي قام بتغيير رقمه المسبق الدفع&nbsp;، أن يسترجع رقمه القديم عن طريق خدمة خليك معنا&nbsp;.</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">14. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لا يمكن للمشترك من إعادة تفعيل الخط في حال كان لديه 5 خطوط أخرى مسجلة باسمه .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">15. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن للمشترك التنازل عن خطه بعد إعادة التفعيل ، و ذلك بعد <u>مرور 30 يوم</u> على إعادة التفعيل .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">16. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن للمشترك تحويل ليرات من الخط بعد إعادة التفعيل ، بدون تحقق شرط استهلاك <b>100 ل.س</b> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">17. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن الاستفادة من الخدمة بالنسبة للمشتركين الأجانب .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">18. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن للمشترك الذي ألغى خطه المسبق الدفع ، أن يعيد تفعيل الخط ( خلال المدة المحددة للاستفادة من خدمة خليك معنا ) .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">19. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن لموظف المركز تقديم خدمة خليك معنا على أي شريحة ، بغض النظر عن نوع </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">HLR</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">20. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">لا يمكن إجراء </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">PD</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> مع خدمة خليك معنا .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">21. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن تحويل الخط المسبق إلى لاحق الدفع بعد إعادة تفعيل الخط بخدمة خليك معنا دون الحاجة للانتظار مدة شهر .</span></p>
<p class="MsoListParagraphCxSpMiddle" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">22. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;لا يمكن الاستفادة من خدمة خليك معنا إلا لصاحب الخط حصراً ,&nbsp; و بالتالي في حال وفاة المشترك لا يمكن تفعيل الخط باسم مشترك آخر حتى مع وجود شهادة الوفاة وحصر الإرث والوكالات .</span></p>
<p class="MsoListParagraphCxSpLast" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l7 level1 lfo4; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-fareast-font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">23. </span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن الاستفادة من خدمة خليك معنا لصاحب الخط حصراً ويمكن قبول الوكالة في حال كان المشترك على قيد الحياة فقط .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SA" style="font-family: 'MTN Brighter Sans Arabic';">ملاحظة هامة :</span></b><span lang="AR-SA" style="font-family: 'MTN Brighter Sans Arabic';"> بعد إلغاء الخط المسبق الدفع يتم تحويل حالة الخط إلى (</span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic';">Suspend</span><span lang="AR-SA" style="font-family: 'MTN Brighter Sans Arabic';">) سيحتاج الخط لمدة قد تصل إلى <b><u>10 أيام كحد أقصى</u></b> لكي يقوم القسم المختص بتحويله إلى حالة (</span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic';">Deactivated</span><span lang="AR-SA" style="font-family: 'MTN Brighter Sans Arabic';">) و بعدها يمكن للمشترك الاستفادة من خدمة خليك معنا , علماً أن القسم المختص سيقوم يوم الأربعاء (من كل أسبوع) بتحويل كل الخطوط المسبقة الدفع (التي تم إلغاؤها في الأسبوع السابق بين يومي الأحد لغاية يوم السبت) من حالة </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic';">Suspend</span><span lang="AR-SA" style="font-family: 'MTN Brighter Sans Arabic';"> إلى </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic';">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">مثال :</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> الخط الذي انتهت فترة تجميده يوم الأحد 01-</span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Jul-2012</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> سيتم تحويله إلى حالة </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Deactivated</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> على برنامج الـ </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CX</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> في يوم الاربعاء 11-</span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Jul-2012</span> <span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">، و بعد التاريخ الأخير يمكن للمشترك الحضور إلى المركز و إعادة تفعيل خطه بخدمة ( خليك معنا ) .</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">&nbsp;</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">يمكن التأكد من تاريخ إلغاء الخط عن طريق برنامج الـ </span><b><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">CX</span></b><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> ضمن : </span><span dir="LTR" lang="EN-GB" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">Customer Information – Contract History</span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;"> :</span></p>
<p dir="RTL">
</p><p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">بعض تسجيلات الـ </span></b><b><span dir="LTR" lang="EN-GB" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;">CRM</span></b><b><span lang="AR-SY" style="font-size: 12.0pt; line-height: 107%; font-family: 'MTN Brighter Sans Arabic'; color: #0070c0; mso-bidi-language: AR-SY;"> :</span></b></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo8; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">استفسار عن حالة خط ملغى</span></p>
<p class="MsoListParagraph" dir="RTL" style="mso-add-space: auto; text-align: right; text-indent: -.25in; mso-list: l3 level1 lfo8; direction: rtl; unicode-bidi: embed; margin: 0in .5in 8.0pt 0in;"><!-- [if !supportLists]--><span lang="EN-GB" style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-language: AR-SY;"><span style="mso-list: Ignore;">·<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-bidi-language: AR-SY;">استفسار عن إمكانية </span><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US; mso-bidi-language: AR-SY;">استرجاع الخط</span></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><b><u><span lang="AR-SY" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US; mso-bidi-language: AR-SY;">ملاحظة : لكل حالة تسجيلة خاصة تتماشى مع طبيعة الاستفسار</span></u></b><b><u></u></b></p>
<p class="MsoNormal" dir="RTL" style="text-align: right; direction: rtl; unicode-bidi: embed;"><span dir="LTR" style="font-family: 'MTN Brighter Sans Arabic'; mso-ansi-language: EN-US; mso-bidi-language: AR-SY;">&nbsp;</span></p>
</div>
    `,

    image: "linear-gradient(135deg, #673AB7, #7E57C2)"

};